{% set name = "CacheControl" %}
{% set version = "0.12.11" %}
{% set sha256 = "a5b9fcc986b184db101aa280b42ecdcdfc524892596f606858e0b7a8b4d9e144" %}

package:
  name: {{ name.lower() }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
      - doesitcache = cachecontrol._cmd:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - requests
    - msgpack-python

test:
  requires:
    - pip
  imports:
    - cachecontrol
  commands:
    - pip check
    - doesitcache --help

about:
  home: https://github.com/ionrock/cachecontrol
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: httplib2 caching algorithms for use with requests
  description: |
    CacheControl is a port of the caching algortihms in httplib2
    for use with requests session object.
  doc_url: http://cachecontrol.readthedocs.org
  doc_source_url: https://github.com/ionrock/cachecontrol/blob/master/docs/index.rst
  dev_url: https://github.com/ionrock/cachecontrol
