{% set name = "CacheControl" %}
{% set version = "0.14.3" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 73e7efec4b06b20d9267b441c1f733664f989fb8688391b670ca812d70795d11

build:
  number: 0
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - flit-core >=3.2,<4
  run:
    - python

outputs:
  - name: cachecontrol
    build:
      skip: true  # [py<37]
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - doesitcache = cachecontrol._cmd:main
    requirements:
      host:
        - pip
        - python
        - flit-core
      run:
        - python
        - requests >=2.16.0
        - msgpack-python >=0.5.2, <2.0.0
    test: &test
      requires:
        - pip
      imports:
        - cachecontrol
      commands:
        - pip check
        - doesitcache --help

  - name: cachecontrol-with-redis
    build:
      skip: true  # [py<37]
    requirements:
      host:
        - pip
        - python
        - flit-core
      run:
        - {{ pin_subpackage("cachecontrol", exact=True) }}
        - python
        - redis-py >=2.10.5
    test: *test

  - name: cachecontrol-with-filecache
    build:
      skip: true  # [py<37]
    requirements:
      host:
        - python
        - pip
        - flit-core
      run:
        - {{ pin_subpackage("cachecontrol", exact=True) }}
        - python
        - filelock >=3.8.0
    test: *test

about:
  home: https://github.com/ionrock/cachecontrol
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: The httplib2 caching algorithms packaged up for use with requests
  description: |
    CacheControl is a port of the caching algorithms in httplib2 for use with
    requests session object.
    It was written because httplib2's better support for caching is often
    mitigated by its lack of thread safety. The same is true of requests
    in terms of caching.
  doc_url: https://cachecontrol.readthedocs.io
  dev_url: https://github.com/ionrock/cachecontrol
